name: CI

on:
    push:
        branches:
            - "main"

jobs:
    check-code:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'
                    coverage: none

            -   name: Cache vendor
                uses: actions/cache@v5
                with:
                    path: vendor
                    key: vendor-${{ hashFiles('composer.lock') }}

            -   name: Install composer
                run: |
                    composer config allow-plugins.pestphp/pest-plugin false
                    composer install \
                      --prefer-dist \
                      --no-interaction \
                      --no-progress \
                      --no-scripts \
                      --optimize-autoloader \
                      --classmap-authoritative

            -   name: Check PHP Code style
                run: composer cs

    tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v6

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.5'
                    coverage: xdebug

            -   name: Cache vendor
                uses: actions/cache@v5
                with:
                    path: vendor
                    key: vendor-${{ hashFiles('composer.lock') }}

            -   name: Install composer
                run: |
                    composer config allow-plugins.pestphp/pest-plugin false
                    composer install \
                      --prefer-dist \
                      --no-interaction \
                      --no-progress \
                      --no-scripts \
                      --optimize-autoloader \
                      --classmap-authoritative

            -   name: Run tests
                run: ./vendor/bin/pest
