name: Sync main with v1.x

on:
    push:
        branches:
            - v1.x

permissions:
    contents: write

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout main
                uses: actions/checkout@v6
                with:
                    ref: main
                    fetch-depth: 0

            -   name: Force reset main to v1.x
                run: |
                    git fetch origin v1.x
                    git reset --hard origin/v1.x
                    git push origin main --force

